/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gtone_express_server_rules_BrexLib */

#ifndef _Included_rules_BrexLib
#define _Included_rules_BrexLib
#ifdef __cplusplus
extern "C" {
#endif

/*  ·ê Parser  */

JNIEXPORT jint JNICALL Java_com_gtone_express.server_rules_BrexLib_checkCondition
(JNIEnv *, jobject, jstring, jbyteArray);
//                    Stmt     msg

JNIEXPORT jint JNICALL Java_com_gtone_express.server_rules_BrexLib_checkResult
(JNIEnv *, jobject, jstring, jintArray, jbyteArray);
//                    Stmt     dType      msg

JNIEXPORT jint JNICALL Java_com_gtone_express_server_rules_BrexLib_checkExp(
		JNIEnv *, jobject, jstring, jbyteArray);
//                    Stmt     msg

/*  Deploy ¿ë  */

/*
 * Class:     com_gtone_express_server_rules_BrexLib
 * Method:    DeployProgram
 * Signature: (Ljava/lang/String;II[Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_gtone_express_server_rules_BrexLib_DeployProgram(
		JNIEnv *, jobject, jstring, jint, jint, jobjectArray, jbyteArray);

/*
 * Class:     com_gtone_express_server_rules_BrexLib
 * Method:    DeployRule
 * Signature: (Ljava/lang/String;II[ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_gtone_express_server_rules_BrexLib_DeployRule(
		JNIEnv *, jobject, jstring, jint, jint, jintArray, jbyteArray);

/*
 * Class:     com_gtone_express_server_rules_BrexLib
 * Method:    DeleteRule
 * Signature: (Ljava/lang/String;II[ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_gtone_express_server_rules_BrexLib_DeleteRule(
		JNIEnv *, jobject, jstring, jint, jint, jintArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
