/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gtone_express_server_rules_SyntaxCheck */

#ifndef _Included_com_gtone_express_server_rules_SyntaxCheck
#define _Included_com_gtone_express_server_rules_SyntaxCheck
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gtone_express_server_rules_SyntaxCheck
 * Method:    DeployProgram
 * Signature: (Ljava/lang/String;II[Ljava/lang/String;[B)I
 */
JNIEXPORT jint JNICALL Java_com_gtone_express_server_rules_SyntaxCheck_DeployProgram(
		JNIEnv *, jclass, jstring, jint, jint, jobjectArray, jbyteArray);

/*
 * Class:     com_gtone_express_server_rules_SyntaxCheck
 * Method:    DeployRule
 * Signature: (Ljava/lang/String;II[I[B)I
 */
JNIEXPORT jint JNICALL Java_com_gtone_express_server_rules_SyntaxCheck_DeployRule(
		JNIEnv *, jclass, jstring, jint, jint, jintArray, jbyteArray);

/*
 * Class:     com_gtone_express_server_rules_SyntaxCheck
 * Method:    DeleteRule
 * Signature: (Ljava/lang/String;II[I[B)I
 */
JNIEXPORT jint JNICALL Java_com_gtone_express_server_rules_SyntaxCheck_DeleteRule(
		JNIEnv *, jclass, jstring, jint, jint, jintArray, jbyteArray);

/*
 * Class:     com_gtone_express_server_rules_SyntaxCheck
 * Method:    getEngineInfo
 * Signature: (Ljava/lang/String;I[I[B)I
 */
JNIEXPORT jint JNICALL Java_com_gtone_express_server_rules_SyntaxCheck_getEngineInfo(
		JNIEnv *, jclass, jstring, jint, jintArray, jbyteArray);

/*
 * Class:     com_gtone_express_server_rules_SyntaxCheck
 * Method:    getEngineDetail
 * Signature: (Ljava/lang/String;I[Ljava/lang/String;[B)I
 */
JNIEXPORT jint JNICALL Java_com_gtone_express_server_rules_SyntaxCheck_getEngineDetail(
		JNIEnv *, jclass, jstring, jint, jobjectArray, jbyteArray);

/*
 * Class:     com_gtone_express_server_rules_SyntaxCheck
 * Method:    checkCondition
 * Signature: (Ljava/lang/String;[B)I
 */
JNIEXPORT jint JNICALL Java_com_gtone_express_server_rules_SyntaxCheck_checkCondition(
		JNIEnv *, jclass, jstring, jbyteArray);

/*
 * Class:     com_gtone_express_server_rules_SyntaxCheck
 * Method:    checkResult
 * Signature: (Ljava/lang/String;[I[B)I
 */
JNIEXPORT jint JNICALL Java_com_gtone_express_server_rules_SyntaxCheck_checkResult(
		JNIEnv *, jclass, jstring, jintArray, jbyteArray);

/*
 * Class:     com_gtone_express_server_rules_SyntaxCheck
 * Method:    checkExp
 * Signature: (Ljava/lang/String;[B)I
 */
JNIEXPORT jint JNICALL Java_com_gtone_express_server_rules_SyntaxCheck_checkExp(
		JNIEnv *, jclass, jstring, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
